about:
  en: About
  fr: À propos
aboutus:
  en: About us
  fr: Qui sommes nous
address:
  en: Address
  fr: Adresse
all:
  en: All
  fr: Tout
articles:
  en: Articles
  fr: Articles
contact:
  en: Contact
  fr: Contact
clients:
  en: Clients
  fr: Clients
education:
  en: Education
  fr: Éducation
email:
  en: Email
  fr: E-mail
emails:
  en: Emails
  fr: E-mails
enquiries:
  en: General enquiries
  fr: Enquêtes
experience:
  en: Experience
  fr: Expérience
home:
  en: Home
  es: Inicio
  fr: Accueil
  de: Startseite
interested:
  en: Glad to see you're interested!
  fr: Merci de votre interrêt
networks:
  en: Social Networks
  fr: Réseaux Sociaux
news:
  en: News
  fr: Nouvelles
notify:
  en: Type your email below and we'll notify you when it's ready. It's just a matter
    of days. Thank You!
  fr: Renseignez votre email et nous vous préviendrons quand c'est prêt d'ici quelques
    jours. Merci!
people:
  en: People
  fr: L'équipe
phone:
  en: Phone
  fr: Téléphone
photos:
  en: Photos
  fr: Photos
press:
  en: Press
  fr: Presse
presscontact:
  en: Press contact
  fr: Contact de Presse
presskits:
  en: Presskits
  fr: Kits de Presse
privacy:
  en: Privacy policy.
  fr: Politique de confidentialité
ready:
  en: Tell me when it's ready!
  fr: Dites moi quand c'est prêt!
rights:
  en: All rights Reserved.
  fr: Tous droits réservés
sales:
  en: Sales
  fr: Ventes
support:
  en: Customer support
  fr: Support Clients
